# NumPy - Numerical Python

In [2]:
import numpy as np

### Criando arrays de 1 dimensão

In [ ]:
a1D = np.array([1, 2, 3])  # função do numpy q cria array

In [ ]:
b1D = np.array([1, 2, 3], dtype = float) # array do tipo float

### Criando arrays de 2 dimensões (matriz)

In [4]:
a2D = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Criando arrays de 3 dimensões

In [5]:
a3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
a3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])



## Propriedades de um array

### Verifica o formato - shape

In [6]:
a3D.shape

(1, 3, 3)

### Verifica o numero de dimensões - dim

In [7]:
a3D.ndim

3

### Verifica o tamanho das dimensões - len

In [8]:
len(a3D) #retorna o tamanho da primeira dimensão

1

In [9]:
len(a3D[0]) #retorna o tamanho da segunda dimensão

3

### Verifica a qtd de elementos - size

In [10]:
a3D.size

9

### Verifica o tipo dos elementos - dtype

In [11]:
a3D.dtype

dtype('int32')

## Indexação e fatiamento

### Acessando elementos específicos

In [17]:
# array de 1 dimensão
a1d = np.random.randint(0,10,10)
a1d[0]

5

In [18]:
# array de 2 dimensões
a2d = np.random.randint(1, 101, (4,5))
a2d[1][2]

40

In [19]:
# array de 3 dimensões
a3d = np.random.random((3,4,6))
a3d[2][0][3]

0.3563455005469286

### Fatiamento

In [20]:
a = a1d[1:5]
a

array([9, 4, 4, 3])

In [21]:
b = a2d[2,1:4] # linha 2 colunas 1,2 e 3
b

array([58, 78, 99])

### Indexação com booleanos

In [22]:
a2d>= 250

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## Manipulando ndarrays

In [27]:
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]
